// customer quote constants
export const GET_RECEIVED_QUOTE_SUCCESS = 'GET_RECEIVED_QUOTE_SUCCESS';
export const GET_RECEIVED_QUOTE_FAILURE = 'GET_RECEIVED_QUOTE_FAILURE';

export const GET_SUBMITTED_QUOTE_SUCCESS = 'GET_SUBMITTED_QUOTE_SUCCESS';
export const GET_SUBMITTED_QUOTE_FAILURE = 'GET_SUBMITTED_QUOTE_FAILURE';

export const GET_DRAFT_QUOTE_SUCCESS = 'GET_DRAFT_QUOTE_SUCCESS';
export const GET_DRAFT_QUOTE_FAILURE = 'GET_DRAFT_QUOTE_FAILURE';

export const SHOW_SPINNER = 'SHOW_SPINNER';
export const HIDE_SPINNER = 'HIDE_SPINNER';

export const TOAST_OPEN = 'TOAST_OPEN';
export const TOAST_CLOSE = 'TOAST_CLOSE';

export const GET_QUOTESUBSCRIPTION_SUCESS = 'GET_QUOTESUBSCRIPTION_SUCESS';
export const GET_QUOTESUBSCRIPTION_FAILURE = 'GET_QUOTESUBSCRIPTION_FAILURE';

export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAILURE = 'AUTH_FAILURE';

export const GET_RECEIVED_COMPANYQUOTE_FAILURE = 'GET_RECEIVED_COMPANYQUOTE_FAILURE';
export const GET_RECEIVED_COMPANYQUOTE_SUCCESS = 'GET_RECEIVED_COMPANYQUOTE_SUCCESS';
export const GET_SUBMITTED_COMPANYQUOTE_SUCCESS = 'GET_SUBMITTED_COMPANYQUOTE_SUCCESS';
export const GET_SUBMITTED_COMPANYQUOTE_FAILURE = 'GET_SUBMITTED_COMPANYQUOTE_FAILURE';
export const GET_COMPANY_POLICY_SUCCESS = 'GET_COMPANY_POLICY_SUCCESS';
export const GET_COMPANY_POLICY_FAILURE = 'GET_COMPANY_POLICY_FAILURE';

export const GET_MY_POLICIES_SUCCESS = 'GET_MY_POLICIES_SUCCESS';
export const GET_MY_POLICIES_FAILURE = 'GET_MY_POLICIES_FAILURE';

export const GET_POLICIE_BY_ID_SUCCESS = 'GET_POLICIE_BY_ID_SUCCESS';
export const GET_POLICIE_BY_ID_FAILURE = 'GET_POLICIE_BY_ID_FAILURE';

// compare policy

export const ADD_TO_COMPARE = 'ADD_TO_COMPARE';
export const CLEAR_COMPARE = 'CLEAR_COMPARE';
export const DELETE_COMPARE = 'DELETE_COMPARE';

export const SHOW_COMPARE_POLICY = 'SHOW_COMPARE_POLICY';
export const HIDE_COMPARE_POLICY = 'HIDE_COMPARE_POLICY';

export const GET_ACTIVE_POLICY_SUCCESS = 'GET_ACTIVE_POLICY_SUCCESS';
export const GET_ACTIVE_POLICY_FAILURE = 'GET_ACTIVE_POLICY_FAILURE';

export const GET_POLICY_SUCCESS = 'GET_POLICY_SUCCESS';
export const GET_POLICY_FAILURE = 'GET_POLICY_FAILURE';

export const GET_ENDORSEMENT_TYPE_SUCCESS = 'GET_ENDORSEMENT_TYPE_SUCCESS';
export const GET_ENDORSEMENT_TYPE_FAILURE = 'GET_ENDORSEMENT_TYPE_FAILURE';

export const GET_CLAIMS_SUCCESS = 'GET_CLAIMS_SUCCESS';
export const GET_CLAIMS_FAILURE = 'GET_CLAIMS_FAILURE';

export const GET_ADJUSTER_CLAIMS_SUCCESS = 'GET_ADJUSTER_CLAIMS_SUCCESS';
export const GET_ADJUSTER_CLAIMS_FAILURE = 'GET_ADJUSTER_CLAIMS_FAILURE';

export const SEARCH_MY_POLICIES = 'SEARCH_MY_POLICIES';

export const CUSTOMER_LANDING_SUCCESS = 'CUSTOMER_LANDING_SUCCESS';
export const CUSTOMER_LANDING_FAILURE = 'CUSTOMER_LANDING_FAILURE';

export const GET_USER_CLAIMS_SUCCESS = 'GET_USER_CLAIMS_SUCCESS';
export const GET_USER_CLAIMS_FAILURE = 'GET_USER_CLAIMS_FAILURE';
